---
# tasks/install.yml (php-protobuf)
# Prefix : php_protobuf

- name: Install prerequirements
  apt:
    name: "{{ php_protobuf_install_packages }}"
    update_cache: yes
    state: present

- name: Install from pecl
  pear:
    name: "pecl/protobuf-{{ php_protobuf_version }}"
    state: present
